products:
  opsman:
    product-version: "2.7.0"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*((iaas))*.yml"

  pas:
    product-version: "2.7.0"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"
    stemcell-iaas: ((iaas))