products:
  opsman:
    product-version: "2.7.0"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*aws*.yml"

  elastic-runtime:
    product-version: "2.7.0"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"
    stemcell-iaas: aws

  pivotal-mysql:
    product-version: "2.6.3"
    pivnet-product-slug: pivotal-mysql
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: aws
